export const EducationDetails = [
  {
    title: "Bachelor of Technology",
    from: "Aug 2016",
    to: "Sep 2020",
    specialization: "Electronics and Communication Engineering",
    institute: "Jain University",
    place: "Banglore",
    state: "Karnataka",
    keyHighlights: [
      "Final Year Project : Design and Implementation of Dual H - shaped PIFA Antenna for 5G Applications.",
      "It is a 5G Antenna with less SAR Value used in Electronic Gadgets",
      "Runner Up in Robo Race Competition",
    ],
    grade: "7.0/10",
  },
  {
    title: "Intermediate",
    from: "Jun 2014",
    to: "Feb 2016",
    specialization: "MPC (Maths, Physics, Chemistry)",
    institute: "Narayana Jr. College",
    place: "Anantapur",
    state: "Andhra Pradesh",
    keyHighlights: ["Runner up in a competition, - A project on Bio Diversity"],
    grade: "91.8%",
  },
  {
    title: "Class 10",
    from: "Jun 2013",
    to: "Mar 2014",
    specialization: "General",
    institute: "Montessori Smart School",
    place: "Anantapur",
    state: "Andhra Pradesh",
    keyHighlights: ["Achieved gold medal in drawing competition"],
    grade: "9.0/10",
  },
];
